### PR TITLE
ignore lib type check

### PR DESCRIPTION
**Pull request by Nekoya3**
## Proposed Changes
Address different ethereum global window definitions in web3modal and metamask/detect-provider packages

## Implementation
Skip type checking inside the library.

Note:
Please note that this support sacrifices some of the accuracy of the type checking.

### CODE REVIEW

**Comment by Nekoya3** [comment]
Hi Team!
You seemed to be having trouble with the Dev channel on Discord, so I'd like to propose a solution.

**Review by vinzvinci — COMMENTED** [review]
Cool 🎉

**Comment by Nekoya3** [comment]
I looked at the Discord and it seems to have already been resolved, so I duplicated it.

It's okay to close the PR.

**Review by stuartwk — APPROVED** [review]

**Comment by stuartwk** [comment]
@Nekoya3 thanks for the PR, merged in. much appreciated.

**Pull request merged**
